services:
  - type: web
    name: super-repay
    env: python
    buildCommand: ""
    startCommand: "gunicorn money_net:app"

  - type: cron
    name: keep-alive-cron
    schedule: "*/10 * * * *"
    env: python
    plan: free
    buildCommand: ""
    startCommand: "curl https://test-10-2h45.onrender.com"
